computer/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'computer'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('home', views.index, name = 'home'),
    # path('brand',views.brand_main_page, name='brand'),
    path('add_computer',views.add_computer, name='add_computer'),
    path('update_computer/<int:id>/',views.update_computer, name='update_computer'),
    path('view_computer/',views.view_computer, name='view_computer'),
    path('add_brand',views.add_brand, name='add_brand'),
    path('view_brand',views.view_brand, name='view_brand'),
    path('update_brand/<int:id>/',views.update_brand, name='update_brand'),
    path('delete_brand/<int:id>/',views.delete_brand, name='delete_brand'),
    path('delete_computer/<int:id>/',views.delete_computer, name='delete_computer'),
    path('delete_specification/<int:id>/',views.delete_specification, name='delete_specification'),
    
    path('add_specification',views.add_specification, name='add_specification'),
    path('view_specification',views.view_specification, name='view_specification'),
    path('update_specification/<int:id>/',views.update_specification, name='update_specification'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('computer.urls', namespace='computer'))
]

templates/add_computer.html
{% extends 'base.html' %} {% block title %}Add Computer{% endblock %} {% load
static %} {% block content %}

<form
  method="post"
  action="{% url 'computer:add_computer' %}"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <div class="form-group row">
    <label
      for="computerGen"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Computer Specification</label
    >
    <div class="col-sm-10">
      <select name="specificationId" id="cars">
        {% for specification in specifications %}

        <option value="{{specification.id}}">
          {{ specification.generation }}
        </option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div class="form-group row">
    <label
      for="computerCode"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Computer Code</label
    >
    <div class="col-sm-10">
      <input
        type="number"
        class="form-control"
        id="computerCode"
        name="computerCode"
        placeholder="Computer Code"
        value="{{computer_code}}"
        required
      />
    </div>
  </div>

  <div class="form-group row">
    <label
      for="quantity"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Quantity</label
    >
    <div class="col-sm-10">
      <input
        type="number"
        min="1"
        max="10000"
        value="{{quantity}}"
        class="form-control"
        id="quantity"
        name="quantity"
        placeholder="Quantity"
        required
      />
    </div>
  </div>
  <div class="form-group row">
    <label
      for="quantity"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Unit Price</label
    >
    <div class="col-sm-10">
      <input
        type="number"
        class="form-control"
        id="unitPrice"
        name="unitPrice"
        placeholder="Unit Price"
        required
      />
    </div>
  </div>

  <div class="form-group row">
    <label
      for="image"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Image</label
    >
    <div class="form-group row">
      <input
        type="file"
        class="form-control-file"
        id="customFile"
        name="files"
        accept="image/*"
        required
        style="margin-left: 30px"
      />
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary btn-lg">Save</button>
    </div>
  </div>

  {% if message != '' %}
  <script>
    {
      alert("{{message}}");
    }
  </script>
  {% endif %}
</form>

{% endblock %}

templates/add_specification.html
{% extends 'base.html' %} {% block title %}Add Specification{% endblock %} {%
load static %} {% block content %}

<form
  method="post"
  action="{% url 'computer:add_specification' %}"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <div class="form-group row">
    <label
      for="brand_name"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Brand Name</label
    >
    <div class="col-sm-10">
      <select name="specificationId" id="brand_name">
        {% for specification in specifications %}

        <option value="{{specification.id}}">
          {{ specification.brand_name }}
        </option>
        {% endfor %}
      </select>
    </div>
  </div>

  <div class="form-group row">
    <label
      for="generation"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Generation</label
    >
    <div class="col-sm-10">
      <input
        type="text"
        class="form-control"
        id="generation"
        name="generation"
        placeholder="Generation"
        required
      />
    </div>
  </div>
  <div class="form-group row">
    <label
      for="min_price"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Minimum Price</label
    >
    <div class="col-sm-10">
      <input
        type="number"
        class="form-control"
        id="min_price"
        name="min_price"
        placeholder="Minimum Price"
        required
      />
    </div>
  </div>
  <div class="form-group row">
    <label
      for="max_price"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Maximum Price</label
    >
    <div class="col-sm-10">
      <input
        type="number"
        class="form-control"
        id="max_price"
        name="max_price"
        placeholder="Maximum Price"
        required
      />
    </div>
  </div>
  <div class="form-group row">
    <label for="ram" class="col-sm-2 col-form-label" style="padding-left: 2rem"
      >RAM</label
    >
    <div class="col-sm-10">
      <input
        type="number"
        class="form-control"
        id="ram"
        name="ram"
        placeholder="RAM"
        required
      />
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary btn-lg">Save</button>
    </div>
  </div>
</form>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    <div class="container">
      <header class="header">
        <div class="header_content">
          <a href="{% url 'computer:home' %}" class="logo">Django Project</a>
        </div>

        <nav class="navbar">
          <ul class="nav_list">
            <li class="nav_item">
              <a href="{% url 'computer:view_brand' %}" class="nav-link"
                >Brand</a
              >
            </li>
          </ul>
          <ul class="nav_list">
            <li class="nav_item">
              <a href="{% url 'computer:view_specification' %}" class="nav-link"
                >Specification</a
              >
            </li>
          </ul>
          <ul class="nav_list">
            <li class="nav_item">
              <a href="{% url 'computer:view_computer' %}" class="nav-link"
                >Computer</a
              >
            </li>
          </ul>

          <!-- <a href="{% url 'computer:view_specification' %}" class="nav-item"
            >Specification</a
          >
          <a href="{% url 'computer:view_computer' %}" class="nav-item">Computer</a> -->
        </nav>
      </header>

      <div class="main" id="content">{% block content %} {% endblock %}</div>
    </div>

    <script src="{% static 'js/index.js' %}"></script>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/brand_main_page.html
{% extends 'base.html' %} {% block title %}Brand{% endblock %} {% load static %}
{% block content %}<a href="{% url 'computer:add_brand' %}">
  <button class="button">Add</button> </a
>{% endblock %}

templates/create.html
{% extends 'base.html' %} {% block title %}Create{% endblock %} {% load static
%} {% block content %}

<form
  method="post"
  action="{% url 'computer:createList' %}"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <div class="form-group row">
    <label
      for="computerCode"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Computer Code</label
    >
    <div class="col-sm-10">
      <input
        type="number"
        class="form-control"
        id="computerCode"
        name="computerCode"
        placeholder="Computer Code"
        value="{{computer_code}}"
        required
      />
    </div>
  </div>

  <div class="form-group row">
    <label
      for="computerGen"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Computer Specification</label
    >
    <div class="col-sm-10">
      <select name="specificationId" id="cars">
        {% for specification in specifications %}

        <option value="{{specification.id}}">
          {{ specification.generation }}
        </option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div class="form-group row">
    <label
      for="quantity"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Quantity</label
    >
    <div class="col-sm-10">
      <input
        type="number"
        min="1"
        max="1000"
        value="{{quantity}}"
        class="form-control"
        id="quantity"
        name="quantity"
        placeholder="Quantity"
        required
      />
    </div>
  </div>
  <div class="form-group row">
    <label
      for="quantity"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Unit Price</label
    >
    <div class="col-sm-10">
      <input
        type="number"
        class="form-control"
        id="unitPrice"
        name="unitPrice"
        placeholder="Unit Price"
        required
      />
    </div>
  </div>

  <input
    type="file"
    name="files"
    id="upload-input"
    class="visually-hidden"
    accept="image/*"
    required
  />

  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary btn-lg">Save</button>
    </div>
  </div>

  {% if message != '' %}
  <script>
    {
      alert("{{message}}");
    }
  </script>
  {% endif %}
</form>

{% endblock %}

templates/create_brand.html
{% extends 'base.html' %} {% block title %}Create{% endblock %} {% load static
%} {% block content %}

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-group row">
    <label
      for="brand_name"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Brand Name</label
    >
    <div class="form-group row">
      <input
        type="text"
        class="form-control"
        id="brand_name"
        name="brand_name"
        placeholder="Brand Name"
        required
      />
    </div>
  </div>

  <div class="form-group row">
    <label
      for="brand_logo"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Logo</label
    >
    <div class="col-sm-10">
      <input
        type="file"
        class="form-control-file"
        id="brand_logo"
        name="brand_logo"
        accept="image/*"
        required
      />
    </div>
  </div>
  <div
    class="form-group row"
    class="col-sm-2 col-form-label"
    style="padding-left: 1rem"
  >
    <div class="col-sm-10" action="{% url 'computer:view_brand' %}">
      <button type="submit" class="btn btn-primary btn-lg">Save</button>
    </div>
  </div>
</form>

{% endblock %}

templates/index.html
{% extends 'base.html' %} {% block title %}Home{% endblock %} {% load static %}
{% block content %} Index Page {% endblock %}

templates/update.html
{% extends 'base.html' %} {% block title %}Create{% endblock %} {% load static
%} {% block content %}

<form
  method="post"
  action="{% url 'computer:updateSuccess' current_specification.id %}"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <div class="form-group row">
    <label
      for="computerCode"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Computer Code</label
    >
    <div class="col-sm-10">
      <input
        type="text"
        class="form-control"
        id="computerCode"
        name="computerCode"
        value="{{current_specification.computer_code}}"
        required
      />
    </div>
  </div>

  <div class="form-group row">
    <label
      for="computerGen"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Computer Specification</label
    >

    <div class="col-sm-10">
      <select name="specificationId" id="cars">
        {% for specification in specifications %}
        <option value="{{specification.id}}">
          {{ specification.generation }}
        </option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div class="form-group row">
    <label
      for="quantity"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Quantity</label
    >
    <div class="col-sm-10">
      <input
        type="number"
        min="1"
        max="1000"
        value="{{current_specification.quantity}}"
        class="form-control"
        id="quantity"
        name="quantity"
        placeholder="Quantity"
        required
      />
    </div>
  </div>
  <div class="form-group row">
    <label
      for="computercode"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Unit Price</label
    >
    <div class="col-sm-10">
      <input
        type="number"
        class="form-control"
        id="unitPrice"
        name="unitPrice"
        value="{{current_specification.unit_rate}}"
        placeholder="Unit Price"
        required
      />
    </div>
    <div class="form-group row">
      <label
        for="computercode"
        class="col-sm-2 col-form-label"
        style="padding-left: 3.5rem; padding-top: 1rem"
        >Replace</label
      >
      <input
        type="file"
        class="col-sm-8 col-form-label"
        name="files"
        id="upload-input"
        class="visually-hidden"
        accept="image/*"
        style="margin-left: 200px; padding-left: 100px"
      />
      <div style="padding-left: 300px">{{current_specification.image}}</div>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary btn-lg">Update</button>
    </div>
  </div>
</form>

{% endblock %}

templates/update_brand.html
{% extends 'base.html' %} {% block title %}Update Brand{% endblock %} {% load
static %} {% block content %}

<form
  method="post"
  action="{%  url 'computer:update_brand' current_specification.id %}"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <div class="form-group row">
    <label
      for="brand_name"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Brand Name</label
    >
    <div class="form-group row">
      <input
        type="text"
        class="form-control"
        id="brand_name"
        name="brand_name"
        placeholder="Brand Name"
        value="{{current_specification.brand_name}}"
        required
      />
    </div>
  </div>

  <div class="form-group row">
    <label
      for="brand_logo"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Logo</label
    >
    <!-- <input type="file" class="form-control" id="customFile" /> -->
    <div class="form-group row">
      <!-- <input type="file" class="form-control-file" id="customFile" name="brand_logo" /> -->
      <input
        type="file"
        class="form-control-file"
        id="brand_logo"
        name="brand_logo"
        accept="image/*"
        required
      />
    </div>
  </div>
  <div style="padding-left: 160px">{{current_specification.logo}}</div>

  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary btn-lg">Save</button>
    </div>
  </div>
</form>

{% endblock %}

templates/update_computer.html
{% extends 'base.html' %} {% block title %}Update Computer{% endblock %} {% load
static %} {% block content %}

<form
  method="post"
  action="{% url 'computer:update_computer' current_specification.id %}"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <div class="form-group row">
    <label
      for="computerCode"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Computer Code</label
    >
    <div class="col-sm-10">
      <input
        type="text"
        class="form-control"
        id="computerCode"
        name="computerCode"
        value="{{current_specification.computer_code}}"
        required
      />
    </div>
  </div>

  <div class="form-group row">
    <label
      for="computerGen"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Computer Specification</label
    >

    <div class="col-sm-10">
      <select name="specificationId" id="cars">
        {% for specification in specifications %}
        <option value="{{specification.id}}">
          {{ specification.generation }}
        </option>
        {% endfor %}
      </select>
    </div>
  </div>

  <div class="form-group row">
    <label
      for="quantity"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Quantity</label
    >
    <div class="col-sm-10">
      <input
        type="number"
        min="1"
        max="1000"
        value="{{current_specification.quantity}}"
        class="form-control"
        id="quantity"
        name="quantity"
        placeholder="Quantity"
        required
      />
    </div>
  </div>

  <div class="form-group row">
    <label
      for="computercode"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Unit Price</label
    >
    <div class="col-sm-10">
      <input
        type="number"
        class="form-control"
        id="unitPrice"
        name="unitPrice"
        value="{{current_specification.unit_rate}}"
        placeholder="Unit Price"
        required
      />
    </div>
  </div>

  <div class="form-group row">
    <label
      for="image"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Replace</label
    >

    <div class="form-group row">
      <input
        type="file"
        class="form-control-file"
        id="customFile"
        name="files"
        accept="image/*"
        required
        style="margin-left: 30px; margin-top: 15px"
      />
    </div>
  </div>

  <div style="padding-left: 195px">{{current_specification.image}}</div>

  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary btn-lg">Update</button>
    </div>
  </div>
</form>

{% endblock %}

templates/update_message.html
{% extends 'base.html' %} {% block title %}Update Success{% endblock %} {% load
static %} {% block content %}

<p>Database updated.</p>
<script>
  {
    alert("Database Updated!");
  }
</script>

{% endblock %}

templates/update_specification.html
{% extends 'base.html' %} {% block title %}Update Specification{% endblock %} {%
load static %} {% block content %}

<form
  method="post"
  action="{% url 'computer:update_specification' current_specification.id %}"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <div class="form-group row">
    <label
      for="brand_name"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Brand Name</label
    >
    <div class="col-sm-10">
      <select name="specificationId" id="brand_name">
        {% for specification in specifications %}

        <option value="{{specification.id}}">
          {{ specification.brand_name }}
        </option>
        {% endfor %}
      </select>
    </div>
  </div>

  <div class="form-group row">
    <label
      for="generation"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Generation</label
    >
    <div class="col-sm-10">
      <input
        type="text"
        class="form-control"
        id="generation"
        name="generation"
        value="{{current_specification.generation}}"
        required
      />
    </div>
  </div>
  <div class="form-group row">
    <label
      for="min_price"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Minimum Price</label
    >
    <div class="col-sm-10">
      <input
        type="number"
        class="form-control"
        id="min_price"
        name="min_price"
        value="{{current_specification.price_min}}"
        required
      />
    </div>
  </div>
  <div class="form-group row">
    <label
      for="max_price"
      class="col-sm-2 col-form-label"
      style="padding-left: 2rem"
      >Maximum Price</label
    >
    <div class="col-sm-10">
      <input
        type="number"
        class="form-control"
        id="max_price"
        name="max_price"
        value="{{current_specification.price_max}}"
        required
      />
    </div>
  </div>
  <div class="form-group row">
    <label for="ram" class="col-sm-2 col-form-label" style="padding-left: 2rem"
      >RAM</label
    >
    <div class="col-sm-10">
      <input
        type="number"
        class="form-control"
        id="ram"
        name="ram"
        value="{{current_specification.ram}}"
        required
      />
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10">
      <button type="submit" class="btn btn-primary btn-lg">Save</button>
    </div>
  </div>
</form>

{% endblock %}

templates/viewList.html
{% extends 'base.html' %} {% block title %}Create{% endblock %} {% load static
%} {%block content%} {%for data in page_obj%}

<div class="row">
  <div class="center-block">
    <div class="bg-image">
      <img
        src="http://localhost:8000/media/{{ data.image }}"
        class="img-fluid"
        alt="{{ data.image }}"
        style="height: 200px; width: 500px; padding: 10px"
      />

      <!-- <div class="d-flex justify-content-center align-items-center h-100">
          <p class="text-white mb-0">
            <form method="post" action="{% url 'computer:delete_image' data.id %}">
           {% csrf_token %}
                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
              
            </form>
          </p>
    
      </div> -->
    </div>
  </div>
  <div class="center-block" style="padding: 0.4rem">
    {{data.specification}}
    <hr />
    Computer Code : {{data.computer_code}} <br />
    Quantity: {{data.quantity}} <br />
    Unit Rate: {{data.unit_rate}} <br />
    Total Price: {{data.total_price}} <br />
    <a href="{% url 'computer:updateList' data.id %}"
      ><button type="submit" class="btn btn-primary">Edit</button></a
    >
  </div>
</div>

{% endfor %}
<div class="pagination">
  <span class="step-links">
    {%if page_obj.has_previous%}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {%endif%}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {%if page_obj.has_next%}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>

{%endblock%}

templates/view_computer.html
{% extends 'base.html' %} {% block title %}View Computer{% endblock %} {% load
static %} {%block content%}
<a href="{% url 'computer:add_computer' %}">
  <button class="button">Add</button>
</a>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Image</th>
      <th scope="col">Computer Code</th>
      <th scope="col">Generation</th>
      <th scope="col">Quantity</th>
      <th scope="col">Unit Price</th>
      <th scope="col">Total Price</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    {%for data in page_obj%}
    <tr>
      <td>
        <img
          src="http://localhost:8000/media/{{ data.image }}"
          class="img-fluid"
          alt="{{ data.image }}"
          style="height: 65px; width: 150px; padding: 2px"
        />
      </td>
      <td>{{data.computer_code}}</td>
      <!-- <td>{{data.generation}}</td> -->

      <td>{{data.specification}}</td>
      <td>{{data.quantity}}</td>
      <td>{{data.unit_rate}}</td>
      <td>{{data.total_price}}</td>
      <td>
        <a href="{% url 'computer:update_computer' data.id %}"
          ><button type="submit" class="btn btn-primary">Edit</button></a
        >
      </td>
      <td>
        <a href="{% url 'computer:delete_computer' data.id %}"
          ><button type="submit" class="btn btn-danger">Delete</button></a
        >
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<div class="pagination">
  <span class="step-links">
    {%if page_obj.has_previous%}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {%endif%}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>

    {%if page_obj.has_next%}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>

{%endblock%}